### ISSUE TITLE
Please add `Access-Control-Allow-Origin *`

### ISSUE THREAD

**Issue by joonazan** [elm/package.elm-lang.org#250]
I am writing a tool that requires information of Elm packages. The easiest way by far is to use package.elm-lang.org, but without that access control header I have to setup a proxy server in order to make requests from a browser. Enabling it for API endpoints that only provide information should not be a security problem.

**Comment by bobwhitelock** [comment]
I need access to similar info in a project I'm working on at the moment. For my use case, since I just need access to the list of packages from `/new-packages` in a static site, it's sufficient to just download this with a separate script and then pass it to my app as a flag; I can see how this would be useful when doing similar things though.

I came across [this similar issue](https://github.com/elm-lang/package.elm-lang.org/issues/50) when I was investigating this, but this was 2 years ago so things may have changed. Like you say, I can't see a big risk from exposing the read-only endpoints apart from the risk of overloading the server, but then this could happen anyway.

**Comment by evancz** [comment]
I do not want people leaning on the Elm servers for their projects. I think it would be better to grab the info you need periodically (like every hour or every day) and do most of the serving from your own setup.
