### ISSUE TITLE
sort packages not only by title, but may by last updated

### ISSUE THREAD

**Issue by muelli** [elm/package.elm-lang.org#261]
Currently, the package list is sorted by the package name. It'd be interesting to sort by last update to get a feeling for the activity in the Elm ecosystem.

**Comment by evancz** [comment]
The freshly updated website should use a better sort order.

**Comment by SidneyNemzer** [comment]
As of right now, the packages are sorted alphabetically but weighted by number of elm-conf appearances by the author.

Sorting happens here:

https://github.com/elm/package.elm-lang.org/blob/a8b9f08c66ddc2a5f784bedbc943f48f6efa9be3/src/backend/Memory.hs#L179

(I think alphabetical is implied because the Map will store packages alphabetically)

Weights are defined at the bottom of the file, here:

https://github.com/elm/package.elm-lang.org/blob/a8b9f08c66ddc2a5f784bedbc943f48f6efa9be3/src/backend/Memory.hs#L223-L324
